### ISSUE TITLE
Timeout fetching venta data

### ISSUE THREAD

**Issue by quenthal** [Michsior14/ha-venta#10]
Home Assistant is logging timeout every now and then:

```
Logger: custom_components.venta.venta
Source: helpers/update_coordinator.py:306
Integration: Venta ([documentation](https://github.com/Michsior14/ha-venta), [issues](https://github.com/Michsior14/ha-venta/issues))
First occurred: 26. tammikuuta 2024 klo 22.21.27 (5 occurrences)
Last logged: 08.11.41

Timeout fetching venta data
```
This is approximately every 1-3 hours. For everyday usage this doesn't matter, as the timeouts are quite short (10s). But still, events are also logged with same time schedule (every thing becomes unavailable for 10s, then come back to life). Signal to WiFi is good, Unifi AP is three meters away. Is there anything I can do to log this further or could these timeouts be somewhat mitigated with allowing longer timeouts? I'm using 0.4.1 with AH55x and HA 2024.1.5.

**Comment by quenthal** [comment]
Closing for now; my fault. It seems that it was connected to AP in totally different side of house...

**Comment by Michsior14** [comment]
I've increased timeout in the latest version as well as added configurable update interval. This could help with fixing yours issues ;)

**Comment by Michsior14** [comment]
~Anything in the logs about this error?~

@HomeAssistant310 Try with [v0.11.5](https://github.com/Michsior14/ha-venta/releases/tag/v0.11.5), should work ;)

**Comment by HomeAssistant310** [comment]
Wow, an almost instant fix ;)

The timeout setting now works correctly, however, I am still getting timeout errors, but it's already less with 15s update intevals. I will increase to 20s and keep you updated, in case it does not solve the issue.
