### ISSUE TITLE
Add mode level 5

### ISSUE THREAD

**Issue by FLeXO21** [Michsior14/ha-venta#28]
The LW60T has 5 fan modes, is it possible to add MODE_LEVEL_5 = "level 5" in constants and humidifier.py
I've tested it and it works for my venta device.

**Comment by Michsior14** [comment]
Hey! Do you know the device id of your model?

**Comment by FLeXO21** [comment]
> Hey! Do you know the device id of your model?

{"Header":{"DeviceType":2,"MacAdress":"f8:f0:05:xx:xx:xx","Hash":"-42","Error":0,"DeviceName":""},"Action":{"Power":true,"FanSpeed":3,"TargetHum":65,"Timer":0,"Boost":false,"SleepMode":false,"ChildLock":false,"Automatic":false,"SysLanguage":5,"CleanLanguage":0,"TempUnit":0,"DisplayLeft":1,"DisplayRight":1,"Reset":0,"ConINet":0,"DelUser":false},"Info":{"SWDisplay":"V2.008","SWPower":"V1.001","SWTouch":"V1.3.0","SWWIFI":"V19.4.8","CleanMode":false,"RelState":[true,true,false,false],"TimerT":0,"OperationT":466954,"DiscIonT":131,"CleaningT":52801,"FilterT":21463,"UVCOnT":0,"UVCOffT":0,"CleaningR":0,"Warnings":64},"Measure":{"Temperature":21.4,"Humidity":55.8,"Dust":19,"WaterLevel":3,"FanRpm":1200}}

![image](https://github.com/Michsior14/ha-venta/assets/28360129/dd6dfe0c-6c52-4f7e-974d-8cecb1cd9b68)
