### ISSUE TITLE
LPH60 door status

### ISSUE THREAD

**Issue by klim123123** [Michsior14/ha-venta#43]
Hello,
There is not door status in ha-venta for some reason.
But if i use Venta app, i can see door status when it opened: Close door
Could it be fixed somehow?
Thank you.

![image](https://github.com/user-attachments/assets/e8688ca5-5e0f-47e8-ad81-aba3581d0f2c)

![image](https://github.com/user-attachments/assets/2370d044-13ae-4c24-b076-cdc47a2d6fc5)

**Comment by klim123123** [comment]
Also no temperature/humidity/pm2.5 data available.

**Comment by klim123123** [comment]
i reloaded integration and now i have 20 entities. but still no door status.

![image](https://github.com/user-attachments/assets/0bc4450d-8e0c-4849-8609-47c3bc8f587c)

**Comment by Michsior14** [comment]
I think this status is represented by warnings. Can you confirm that it's always `4` if you have the door open?

**Comment by klim123123** [comment]
Yes, i can confirm i see always `4` if door is open.
Is this mean warning number 4 or there are 4 warnings?

**Comment by Michsior14** [comment]
I just find out this in the resource files one of the users sent me in the past:

```json
{
      "name": "Warnings",
      "type": "integer",
      "description": "Displayed warnings on the display. Values are bit coded. Several Values can be displayed at once.",
      "values": [
        {
          "value": 0,
          "type": "integer",
          "description": "No warning"
        },
        {
          "value": 1,
          "type": "integer",
          "description": "Fill tank (red)"
        },
        {
          "value": 2,
          "type": "integer",
          "description": "Fill tank (yellow)"
        },
        {
          "value": 4,
          "type": "integer",
          "description": "Close door"
        },
        {
          "value": 16,
          "type": "integer",
          "description": "Change air-filter",
          "parameter_ref": "FilterT"
        },
        {
          "value": 32,
          "type": "integer",
          "description": "Change hygiene-disc",
          "parameter_ref": "DiscIonT"
        },
        {
          "value": 64,
          "type": "integer",
          "description": "Cleaning (required)",
          "parameter_ref": "CleaningT"
        }
      ]
    }
```

I finally need to start the bigger refactoring to handle all devices separately, but I don't know when this will occur.

**Comment by klim123123** [comment]
Thank you so much!!!!
And thank you for the project!!!

**Comment by Michsior14** [comment]
Should be available in the latest release!
