### ISSUE TITLE
Support for LW60

### ISSUE THREAD

**Issue by FLeXO21** [Michsior14/ha-venta#5]
Is it possible to support the LW60 models?
I've been using OpenHAB intergration in HA to intergrate my LW60 [https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.ventaair](url)

**Comment by grzegor** [comment]
Bit fancier than ours, @Michsior14 

Available actions: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.ventaair/src/main/java/org/openhab/binding/ventaair/internal/message/action/AllActions.java#L21

Response params: https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.ventaair/src/main/java/org/openhab/binding/ventaair/internal/message/dto/Info.java#L23

Also found AH902 resposnes (very similar device), device type 12, no `ProtocolV` in JSON: https://github.com/openhab/openhab-addons/issues/11791

**Comment by Michsior14** [comment]
@FLeXO21 Could you check if `Action` endpoint also returns current data for your device?

```
$ curl -H "Content-Type: application/json" -X POST "<yours-device-ip>:48000/Action"
```

**Comment by FLeXO21** [comment]
> @FLeXO21 Could you check if `Action` endpoint also returns current data for your device?
> 
> ```
> $ curl -H "Content-Type: application/json" -X POST "<yours-device-ip>:48000/Action"
> ```
This is what i get:

`curl -H "Content-Type: application/json" -X POST "192.168.111.234:48000/Action"
Protocol failure
Command line too long`

**Comment by Michsior14** [comment]
Oh, so it's fully over UDP, somehow I thought it's used only for discovery... Overall this might complicate things since I have no testing device.

**Comment by Michsior14** [comment]
If anyone is able to work on this (with the device) it would be really nice. PRs are welcome :)

**Comment by EinzellerXD** [comment]
Hi
my parents have a Venta AH902.
I decided to play around with it a bit, after reading your code and the openHab implementation.
the Communication is indeed not through UDP, it is through TCP. You could use UDP for discovery, as you suspected.

The way, these Humidifiers talk is way more specific, than the other models. It is very important, that the Packets are built in a specific way. I couldn't get this to work with aiohttp or curl. Instead I used socket and "built" the packet by hand (just for testing).
So, the Port used for communication is 48000. and for the Status you have to use GET and endport Complete.
for the Action you can use POST and endport Action.

The Packet can't have any of the default http headers (not even the version of http). 

So, the Packets have to look like this:
![grafik](https://github.com/Michsior14/ha-venta/assets/84469649/c6eaf7ca-798b-4cbb-9696-0f42f9637e48)

So the python code, that I had success with is this:

```
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("192.168.2.173", 48000))

request = 'GET /Complete \r\nContent-Lenght: Content-Length: 98 \r\n{"Header":{"DeviceType":12,"MacAdress":"xx:xx:xx:xx:xx:d4","Hash":"-42","Error":0,"DeviceName":""}'

s.send(request.encode())
response = s.recv(4096)
print(response.decode())

```

I hope this helps, because I don't know how to implement this in the current version of your integration.

**Comment by FLeXO21** [comment]
i can confirm this also works on the LW60

OK /Complete
Content-Length: 704

{"Header":{"DeviceType":2,"MacAdress":"xx:xx:xx:xx:xx:xx","Hash":"-42","Error":0,"DeviceName":""},"Action":{"Power":true,"FanSpeed":2,"Targ                                      etHum":55,"Timer":0,"Boost":false,"SleepMode":false,"ChildLock":false,"Automatic":false,"SysLanguage":5,"CleanLanguage":0,"TempUnit":0,"Dis                                      playLeft":0,"DisplayRight":0,"Reset":0,"ConINet":0,"DelUser":false},"Info":{"SWDisplay":"V2.008","SWPower":"V1.001","SWTouch":"V1.3.0","SWW                                      IFI":"V19.4.8","CleanMode":false,"RelState":[true,false,false,false],"TimerT":0,"OperationT":456826,"DiscIonT":17430,"CleaningT":52801,"Fil                                      terT":16405,"UVCOnT":0,"UVCOffT":0,"CleaningR":0,"Warnings":66},"Measure":{"Temperature":21.4,"Humidity":54.2,"Dust":7,"WaterLevel":1,"FanR                                      pm":800}}

**Comment by Michsior14** [comment]
@EinzellerXD Thanks for checking this out. Could any of you please try to run bellow code? I think we could skip low level socket communication (just for code maintenance) if it's all about headers:

```python
import aiohttp
import asyncio

async def fetch(client):
    async with client.get("192.168.2.173:48000/Complete", skip_auto_headers=true) as resp:
        assert resp.status == 200
        return await resp.text()

async def main():
    async with aiohttp.ClientSession() as client:
        response = await fetch(client)
        print(response)

asyncio.run(main())
```

**Comment by EinzellerXD** [comment]
I tried this
so, you have to give it a list of headers to skip generating.
but I can only skip the following headers:
`skip_auto_headers=['User-Agent','Accept-Encoding','Accept']`
The Host and the HTTP Version are still there.

It sadly seems like we can't use aiohttp :(

But the way you are implementing it in your PR is just like I imagined, how it would work out.

I'm really looking forward to using this integration. Finally no more loud Humidifier during watching TV.

**Comment by Michsior14** [comment]
Published as [beta](https://github.com/Michsior14/ha-venta/releases/tag/v0.5.1-beta.0), please test.
