### ISSUE TITLE
feat(L*60,LW62,A*902): relay states sensors

### ISSUE THREAD

**Issue by Michsior14** [Michsior14/ha-venta#52]
Since we have now the structure of relay states property and the description of each value those sensors can be added to bunch of devices.

Property definition:
```json
{
  "name": "RelState",
  "type": "array",
  "description": "States of Relais (4 states: Lüfter, Plattenstapel, UVC, Ventil). True if on and False if off."
}
```

Example response:
```json
{
  "Info": {
    "RelState": [true, false, false, false],
  }
}

```

**Comment by klim123123** [comment]
Is it possible to control relays somehow?
I'm doing project to auto-full Venta 60,62 without buying super expensive version.

**Comment by Michsior14** [comment]
I don't think so, couldn't find any information about such action being accepted: [LW60](https://github.com/Michsior14/ha-venta/blob/main/resources/settings/003.json), [LW62](https://github.com/Michsior14/ha-venta/blob/main/resources/settings/005.json)
