### ISSUE TITLE
Venta LPH60 shows fahrenheit temperature instead of celsius

### ISSUE THREAD

**Issue by klim123123** [Michsior14/ha-venta#57]
In Home Assistant it's show the digits in Fahrenheit, but symbol is C.
78.9 F is exactly 26.1 C
how to switch to Celsius digits in Home Assistant ?
Thank you

![image](https://github.com/user-attachments/assets/7ae86991-2024-43ca-85c5-d313d3518f17)
![image](https://github.com/user-attachments/assets/f4c1b53c-b5b7-4d68-850f-e26983a78ca9)

**Comment by Michsior14** [comment]
Could you please enable the debug mode for integration wait for one refresh and attach the log?

I assume this is possible if the device has Fahrenheit set in the parameter store, but would need the confirmation.

**Comment by klim123123** [comment]
`{"Header":{"DeviceType":2,"MacAdress":"xx:f0:05:xx:xx:xx","Hash":"-42","Error":0,"DeviceName":""},"Action":{"Power":true,"FanSpeed":1,"TargetHum":70,"Timer":0,"Boost":false,"SleepMode":false,"ChildLock":false,"Automatic":false,"SysLanguage":7,"CleanLanguage":2,"TempUnit":1,"DisplayLeft":0,"DisplayRight":0,"Reset":0,"ConINet":0,"DelUser":false},"Info":{"SWDisplay":"V2.013","SWPower":"V1.001","SWTouch":"V1.3.0","SWWIFI":"V19.4.8","CleanMode":false,"RelState":[false,false,false,false],"TimerT":0,"OperationT":243326,"DiscIonT":203,"CleaningT":232,"FilterT":99,"UVCOnT":0,"UVCOffT":0,"CleaningR":0,"Warnings":1},"Measure":{"Temperature":79.1,"Humidity":44.7,"Dust":1,"WaterLevel":2,"FanRpm":0}}`

**Comment by Michsior14** [comment]
Yeah, as suspected temperature unit is set as imperial:

```json
  {
    "name": "TempUnit",
    "type": "integer",
    "description": "Display unit of temperature.",
    "values": [
      {
        "value": 0,
        "type": "integer",
        "description": "Metric"
      },
      {
        "value": 1,
        "type": "integer",
        "description": "Imperical"
      }
    ]
  }
```

I think we can make it work by always converting to Celcius in this case / or setting different unit during the native value set. Let me check how it works as there were some changes in this area recently on HA side.

**Comment by Michsior14** [comment]
Please check the v0.10.0 release.

**Comment by klim123123** [comment]
Thank you. Is it how it suppose to be? If i need Celciuse, do i need to convert myself?

![image](https://github.com/user-attachments/assets/1e802fe6-44a6-4dfd-8e5c-2639ccdbde42)

**Comment by Michsior14** [comment]
Nope, I've used the wrong scope for the `TempUnit`, should be fixed in the next 5 minutes :)

**Comment by klim123123** [comment]
Before updating, I just noticed, i have this.
![image](https://github.com/user-attachments/assets/fceb67be-97ba-49b2-a832-5fb465e8c6ba)

**Comment by klim123123** [comment]
After update, all good. Thank you.
![image](https://github.com/user-attachments/assets/200f8bd5-3fd7-4686-a23d-e8f74f5d1686)
