### ISSUE TITLE
Feature Request: Make on/off and Mode a single entity

### ISSUE THREAD

**Issue by MegaBarf** [Michsior14/ha-venta#6]
Hi

great work! I was working on something like that but more complicated as I'm not good at programming ;-)
I was trying to get it run as a rest sensor via the api but I never had the time to actually get this to work.

I would like to have the on/off and the modes as single entity not as "controls" to use it for my functions.

My plan is to turn the device on and off or change the mode via an scheduler and the automation. I'm not using the auto humidity function.

Thank you so much.

**Comment by Michsior14** [comment]
Hey,

I am not sure what do you mean, this should be already available via standard home assistant services e.g. `humidifier.turn_on` / `humidifer.turn_off` / `humidifier.set_mode` that you can run in automation. 

Is this what you need?

**Comment by MegaBarf** [comment]
Hi.

Thank you for your fast reply. I'm relatively new to home assistant and I just found the services ;-)

I tried setting up an automation with  humidifier.turn_on / humidifer.turn_off and a toggle helper but it's not working.
I tried to call the service at the development tools / services tab but my humidifier (AH555) is not responding. Your card works perfectly fine.

Could it be related to https://github.com/Michsior14/ha-venta/issues/1 where you have to send the complete informations?

$ curl -H "Content-Type: application/json" -X POST "$VENTA_LOCAL_IP/api/telemetry?request=set" -d '{
    "Power": 0,
    "Automatic": 0,
    "SleepMode": 0,
    "FanSpeed": 1,
    "Action": "control"
}'

**Comment by Michsior14** [comment]
Strange, this is exactly the same functionality that the humidifier entity uses. By default `turn_on/off` sends everything as mentioned in #1. What happens if you use `humidifier.set_mode` with `level 1`? Maybe there is something different in AH555 :/

**Comment by MegaBarf** [comment]
Hi

nothing happens, see picture

![image](https://github.com/Michsior14/ha-venta/assets/125373879/9dd12eb0-0811-4e16-95d5-54c1523c0e2a)

I switched to YAML mode, see second picture. Could it be that there is something missing? I'm mor a Hardware than a Software guy ;-)

![image](https://github.com/Michsior14/ha-venta/assets/125373879/2a326ddc-d919-46d7-a14a-f1a42d95ee6a)

Happy new Year!

**Comment by Michsior14** [comment]
You need to specify either device or an entity (blue or green button in graphic mode / proper ids in yaml mode). This is the same for on/off service.

**Comment by MegaBarf** [comment]
Ahh damnit...

those buttons were so obvious that accidentally I ignored them even in the automation...
Now it's working, thank you very much.

I guess the bug sat in front of the screen again.

Happy new Year

**Comment by Michsior14** [comment]
Great it works ;)

Happy new year!
