### ISSUE TITLE
Venta humidifier LW74

### ISSUE THREAD

**Issue by wimweiss** [Michsior14/ha-venta#70]
The data of the humidifier is not correctly indicated in HA compaired to the data in the Venta app.
89 days disk replacement and 150 days start cleaning in Venta app and respectively 105 and 166 days in HA.

Other issue is that the ventilator speed, temperature and humidity are froozen when I switch off the humidifier via HA 

**Versions (please complete the following information):**
 - HomeAssistant: latest version 2024.11.3
 - ha-venta: 0.11.0

**Comment by Michsior14** [comment]
Do you know the max days for those parameters? We are solely using the values provided by users for LW73/LW74 right now. They mention 6 months for cleaning and around 4 months for disks, but we well we need days ;)

If you switch the humidifier via screen, are you still able to see reports for temperature/humidity?

**Comment by Michsior14** [comment]
Also I've just checked and it seems that at least for LW7x series, those values are not changed on the device itself when it's off. So there is not really anything I can do about it here.

**Comment by wimweiss** [comment]
> Do you know the max days for those parameters? We are solely using the values provided by users for LW73/LW74 right now. They mention 6 months for cleaning and around 4 months for disks, but well we need days ;)
> 
> If you switch the humidifier via screen, are you still able to see reports for temperature/humidity?
1. Looks like the off-set is -2 days for both. 
2. Values are fixed when I switch off.

**Comment by Michsior14** [comment]
Please check v0.11.2, there seemed to be an mismatch of resolution times in the documentation.
