### ISSUE TITLE
AS150 AirSense Pro no longer reports CO2

### ISSUE THREAD

**Issue by johan-de-jong** [Michsior14/ha-venta#71]
**Describe the bug**
AS150 AirSense Pro no longer reports CO2, even though a CO2 value is reported by the device.

**To Reproduce**
Look at the CO2 entity.

**Expected behavior**
I expect to see the CO2 value as reported by the device.

**Screenshots**

![image](https://github.com/user-attachments/assets/1d594db6-4f26-484d-90ac-9f7f34a05de3)

![image](https://github.com/user-attachments/assets/044dbb25-8a7d-4a03-bfca-d91c2397a45e)

<pre>
$ curl -s http://AirSense.fritz.box/sensordata.json | jq
{
  "Header": {
    "DeviceId": "40:91:51:xx:xx:xx",
    "DeviceType": 150,
    "ProtocolV": "3"
  },
  "Info": {
    "FirmwareVersion": "0.2-cb32b89-Nov 16 2021",
    "CertificateSHA1": "191ebc14e6b0d72785da806bc0f52e57a3258e59"
  },
  "Measure": {
    "Time": 1733145990,
    "Temperature": 20.99,
    "Humidity": 47.26,
    "Co2": 639.00,
    "Voc": 85.00,
    "Hcho": 4.40,
    "Pm1u0": 0.00,
    "Pm2u5": 0.00,
    "Pm10u": 0.00,
    "Particles0u3": 3.00,
    "Particles0u5": 1.00,
    "Particles1u0": 0.00,
    "Particles2u5": 0.00,
    "Particles5u0": 0.00,
    "Particles10u": 0.00,
    "SensorStatus": "0000001F"
  }
}</pre>

**Versions (please complete the following information):**
 - HomeAssistant: 
Core: 2024.11.3
Supervisor: 2024.11.4
Operating System: 13.2
Frontend: 20241106.2
 - ha-venta: v0.11.0

**Comment by Michsior14** [comment]
Please try v0.11.1.
